#!/bin/sh

# Author: Eric Thomas
# CMSC495 7384
# Group: A
# Date: Nov 23'
# Platform: Debian Linux

# Get the absolute path to the root of the Git repository
REPO_ROOT=$(git rev-parse --show-toplevel)

# Construct the absolute path to config/versions.txt
VERSION_FILE="${REPO_ROOT}/config/version.txt"

# Stash uncommitted changes, keeping the index (staged changes)
git stash -q --keep-index

# Get the commit hash
COMMIT_HASH=$(git rev-parse --short HEAD)

# Restore the stashed changes
git stash pop -q

echo $COMMIT_HASH > "$VERSION_FILE"

# Add versions.txt to the staging area
git add "$VERSION_FILE"

# The git commit will continue